### ISSUE TITLE
How to get power metric after inferencing the models on TDA4VM.

### ISSUE THREAD

**Issue by chayy93** [TexasInstruments/edgeai-app-stack#2]
I was able to run the models by using the following command "./app_edgeai.py ../configs/image_classification.yaml" and got the performance metrics like FPS, dl-infer time and total time etc., but in order to calculate the inference power is there any reference GitHub pages or any information, can you please point it to me.

**Comment by ravi-rahul** [comment]
Getting power measurement is not supported 

You can use a typeC power meter
https://www.digikey.in/en/products/detail/pimoroni-ltd/1778-TST001-ND/13537105?utm_adgroup=&utm_source=google&utm_medium=cpc&utm_campaign=PMax%20Shopping_Product_Low%20ROAS&utm_term=&productid=13537105&utm_content=&utm_id=go_cmp-20120530922_adg-_ad-__dev-c_ext-_prd-13537105_sig-CjwKCAjw59q2BhBOEiwAKc0ijWLTomYQ9pkKuGtmGmkSuKG-wuN5Rmdtia7VsYRJmlDAeJwTsr8IoBoCIv4QAvD_BwE&gad_source=1&gclid=CjwKCAjw59q2BhBOEiwAKc0ijWLTomYQ9pkKuGtmGmkSuKG-wuN5Rmdtia7VsYRJmlDAeJwTsr8IoBoCIv4QAvD_BwE
