### ISSUE TITLE
am62a install dependencies failed

### ISSUE THREAD

**Issue by Longtimenoc** [TexasInstruments/edgeai-app-stack#6]
There is a mistake in file https://github.com/TexasInstruments/edgeai-app-stack/blob/main/setup.sh line 27:
`mv tisdk-edgeai-image-am62axx-evm.tar.xz targetfs.tar.xz`

The name of the downloaded file should be tisdk-edgeai-image-am62axx-evm.**wic.xz** rather than tisdk-edgeai-image-am62axx-evm.**tar.xz**, so this command can not run, and an error will be reported:
> mv: cannot stat 'tisdk-edgeai-image-am62axx-evm.tar.xz': No such file or directory.

If the correct file name tisdk-edgeai-image-am62axx-evm.**wic.xz** is used, than the command bellow:
`tar xf ../targetfs.tar.xz > /dev/null`
will report an error:
> tar: This does not look like a tar archive
> tar: Skipping to next header
> tar: Exiting with failure status due to previous errors

It is reasonable for .wic file is an image rather than a tar archive file.
How can I extract files from this .wic image, or get the right tar archive file: tisdk-edgeai-image-am62axx-evm.**tar.xz** ?

**Comment by ravi-rahul** [comment]
Hi @Longtimenoc 

For AM62A tar is not published directly
You can install the linux installer
https://dr-download.ti.com/software-development/software-development-kit-sdk/MD-D37Ls3JjkT/10.00.00.08/ti-processor-sdk-linux-edgeai-am62a-evm-10_00_00_08-Linux-x86-Install.bin

Tar file is packaged in the installer under $(INSTALLER)/filesystem

Will fix this in upcoming releases

Regards
@ravi-rahul
